apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: shared-postgres-dev
  labels:
    app.kubernetes.io/name: shared-postgres
    app.kubernetes.io/part-of: infra
    environment: dev
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: tiny
      owner: tiny

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

  monitoring:
    enablePodMonitor: true
