apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
  namespace: shared-postgres-dev
spec:
  configuration:
    destinationPath: s3://cnpg-backups/

    endpointURL: http://minio.minio.svc.cluster.local:9000

    s3Credentials:
      accessKeyId:
        name: minio-backup-creds
        key: ACCESS_KEY_ID

      secretAccessKey:
        name: minio-backup-creds
        key: ACCESS_SECRET_KEY
