apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-pitr
  namespace: shared-pitr
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 5Gi

  bootstrap:
    recovery:
      source: shared-postgres-backup
      recoveryTarget:
        targetTime: "2026-05-31T08:41:32.188148Z"

  externalClusters:
    - name: shared-postgres-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-store
          serverName: shared-postgres
