replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    memory: 128Mi
