replicaCount: 1

image:
  repository: ghcr.io/yinkaolotin/tiny
  pullPolicy: IfNotPresent
  tag: "0.1.0"

service:
  targetPort: 8080
  port: 80

env:
  SERVICE_NAME: tiny
  SERVICE_ENV: dev
  HTTP_PORT: "8080"
  LOG_LEVEL: info
  DATA_DIR: /data

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-path

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

imagePullSecrets:
  - name: ghcr-pull-secret

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
  labels:
    release: kube-prometheus

prometheusRule:
  enabled: true
  labels:
    release: kube-prometheus

# then add <master-ip> tiny.local to /etc/hosts
# curl -H "Host: tiny.local" <master-ip>:32080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: tiny.local
      paths:
        - path: /
          pathType: Prefix

database:
  enabled: true
  host: shared-postgres-rw.shared-postgres-dev.svc.cluster.local
  port: 5432
  name: tiny
  user: tiny
  # Secret expected inside tiny-dev namespace
  existingSecret: tiny-postgres-credentials
  # key inside the Secret
  passwordKey: password
