apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 85.3.0
      helm:
        releaseName: kube-prometheus
        valueFiles:
          - $values/infra/monitoring/kube-prometheus/values.yaml

    - repoURL: git@github.com:yinkaolotin/homelab.git
      targetRevision: refs/heads/main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
