apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://helm.min.io/
      chart: minio
      targetRevision: 5.4.0
      helm:
        valueFiles:
          - $values/infra/backup/minio/values.yaml

    - repoURL: git@github.com:yinkaolotin/homelab.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
