apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:yinkaolotin/homelab.git
    targetRevision: main
    path: infra/storage/postgres/shared-dev

  destination:
    server: https://kubernetes.default.svc
    namespace: shared-postgres-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
