apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiny-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yinkaolotin/homelab.git
    targetRevision: HEAD
    path: services/tiny/charts/tiny
    helm:
      releaseName: tiny
      valueFiles:
        - ../../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tiny-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
